apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  #name: letsencrypt-staging01
spec:
  acme:
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lwangapaul23@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-com-private-key
      #name: letsencrypt-staging-private-key
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            accessKeyID: AKIAYJ2APMF7DJ6KA44U
            secretAccessKeySecretRef:
              key: secret-access-key
              name: aws-route53-secret
            hostedZoneID: Z023075927QMGEOOXS05Z