apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-cert
  namespace: default
spec:
  secretName: testapp-staging-cert-com-tls
  issuerRef:
    name: letsencrypt-staging01
    kind: ClusterIssuer
  dnsNames:
    - testk8app.paulgobero.com