apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`testk8app.paulgobero.com`) 
      kind: Rule
      services:
        - name: whoami
          kind: Service
          port: 80