apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`testk8app.paulgobero.com`) 
      kind: Rule
      services:
        - name: whoami
          kind: Service
          port: whoamihttp
  tls:
    certResolver: letsencrypt-staging01
    secretName: testapp-staging-cert-com-tls